In [18]:
from scipy import constants
print(constants.pi)

# print(dir(constants))

3.141592653589793


In [17]:
import scipy
import math

def eqn(x):
  return x + math.tan(x) - scipy.constants.pi

myroot = root(eqn, 0)

print(myroot.x)
print(myroot)


[5.32572446e-10]
    fjac: array([[-1.]])
     fun: array([-3.14159265])
 message: 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.'
    nfev: 13
     qtf: array([3.14159265])
       r: array([-2.])
  status: 5
 success: False
       x: array([5.32572446e-10])


In [19]:
def eqn(x):
  return x**2 + x + 2

mymin = scipy.optimize.minimize(eqn, 0, method='BFGS')

print(mymin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [20]:
# fancy example
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [21]:
# connected components
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


In [22]:
# Distances in SciPy
from scipy.spatial.distance import euclidean

p1 = (1, 0)
p2 = (10, 2)

res = euclidean(p1, p2)

print(res)

9.219544457292887


In [23]:
from scipy.spatial.distance import cityblock

p1 = (1, 0)
p2 = (10, 2)

res = cityblock(p1, p2)

print(res)

11


In [24]:
from scipy.spatial.distance import cosine

p1 = (1, 0)
p2 = (10, 2)

res = cosine(p1, p2)

print(res)

0.019419324309079777


In [25]:
from scipy.spatial.distance import hamming

p1 = (True, False, True)
p2 = (False, True, True)

res = hamming(p1, p2)

print(res)

0.6666666666666666


In [26]:
# Interpolation

from scipy.interpolate import interp1d
import numpy as np

xs = np.arange(10)
ys = 2*xs + 1

# print(xs)
# print(ys)

interp_func = interp1d(xs, ys)
# print(np.arange(2.1, 3, 0.1))

newarr = interp_func(np.arange(2.1, 3, 0.1))


print(newarr)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]


In [28]:
# Spline Interpolation
from scipy.interpolate import UnivariateSpline

xs = np.arange(10)
ys = xs**2 + np.sin(xs) + 1

interp_func = UnivariateSpline(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))

print(newarr)

[5.62826474 6.03987348 6.47131994 6.92265019 7.3939103  7.88514634
 8.39640439 8.92773053 9.47917082]


In [29]:
# T-test
import numpy as np
from scipy.stats import ttest_ind

v1 = np.random.normal(size=100)
v2 = np.random.normal(size=100)

res = ttest_ind(v1, v2)

print(res)

Ttest_indResult(statistic=1.0665692367330506, pvalue=0.28746517183530845)


In [30]:
from scipy.stats import kstest

v = np.random.normal(size=100)

res = kstest(v, 'norm')

print(res)

KstestResult(statistic=0.07295579902972216, pvalue=0.6347585096569395)


In [31]:
from scipy.stats import describe

v = np.random.normal(size=100)
res = describe(v)

print(res)

DescribeResult(nobs=100, minmax=(-2.543110980647795, 2.4638947873966215), mean=-0.14377380266129738, variance=0.8746007788531088, skewness=0.3369639294154419, kurtosis=-0.08289217654154823)


In [34]:
from scipy.stats import skew, kurtosis
from scipy.stats import normaltest

v = np.random.normal(size=100)

print(skew(v))
print(kurtosis(v))

print(normaltest(v))


0.09174135825321654
-0.3579940228431999
NormaltestResult(statistic=0.5307509781896398, pvalue=0.7669179265863639)
